### ISSUE TITLE
jupyter notebook codes from Jupytercon talk 2018

### ISSUE THREAD

**Issue by cherepanovic** [ChakriCherukuri/mlviz#5]
are the jupyter notebook codes from [Jupytercon talk 2018](https://www.youtube.com/watch?v=1XTMkcrVyQg) somewhere available? (I am interested in NeuralNetBuilder.ipynb)

thank a lot!

**Comment by afonit** [comment]
@cherepanovic ,
This one here?
https://github.com/ChakriCherukuri/mlviz/blob/master/neural-net-builder/Neural%20Net%20Builder.ipynb

**Comment by ChakriCherukuri** [comment]
@cherepanovic @afonit 
sorry for the late response: The updated nb is here
https://github.com/ChakriCherukuri/mlviz/blob/master/notebooks/deep-learning/neural-net-builder/neural-net-builder.ipynb
